#!/bin/bash

set -euo pipefail

#msg=''
#
#for i in {1..10}; do
#    msg=`printf $msg"{\"ID\":$id}\n"`
#done
#
#resp=`curl -s -l http://localhost:2379/v3alpha/lease/keepalive -H "Grpc-Metadata-NoFlush: True" -H "transfer-encoding: chunked" -XPOST --data-binary $msg`
#
#echo "$resp"

function keepalive {
        echo -e -n "POST /v3alpha/lease/keepalive HTTP/1.1\x0d\x0a"
        echo -e -n "Host: 127.0.0.1\x0d\x0a"
	#	echo -e -n "Connection: keep-alive\x0d\x0a"
        echo -e -n "Transfer-Encoding: chunked\x0d\x0a"
#		echo -e -n "Grpc-Metadata-AutoFlush: True\x0d\x0a"
		echo -e -n "Connection: close\x0d\x0a"
        echo -e -n "\x0d\x0a"
        msg="{\"ID\":$id}"
        len=`printf "%x" $(echo -e -n "$msg" | wc -c)`
        for a in `seq 1 1000`; do
                echo -e -n "$len\x0d\x0a"
                echo -e -n "$msg\x0d\x0a"
                sleep 0.1s
        done
        echo -e -n "0\x0d\x0a"
        echo -e -n "\x0d\x0a"
}

resp=`curl -s -l http://localhost:2379/v3alpha/lease/grant -XPOST -d'{"TTL": 120}'`
id=`echo $resp | tr ',' '\n' | grep ID | cut -f2 -d':'`
echo "got id $id..."
keepalive $id | nc localhost 2379


